name : Super-Linter

on : push 

jobs:
  super-lint:
    name: Link code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        user: actions/checkout@v2

      - name: Run Super-liner
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
